#!/bin/sh
set -e

node_modules/.bin/istanbul cover \
  node_modules/.bin/_mocha -- \
    --compilers coffee:coffee-script \
    --require coffee-script/register \
    --reporter spec \
    --require test/helper.coffee
