#!/bin/sh
set -e

node_modules/.bin/istanbul cover \
  node_modules/.bin/_mocha -- \
    --compilers coffee:coffeescript \
    --require coffeescript/register \
    --reporter spec \
    --require test/helper.coffee
