#!/bin/bash
set -e

# normal files
./node_modules/.bin/coffee -co dist/ source/

# build lexer
node_modules/.bin/jison-lex -o dist/parser/lexer.js source/parser/jadelet.jisonlex
echo 'module.exports = lexer;' >> dist/parser/lexer.js

# parser
script/generate-parser

# cli
mkdir -p bin
BIN="bin/jadelet"
echo "#!/usr/bin/env node" | cat - dist/cli.js > "$BIN"
chmod +x "$BIN"
