#!/bin/bash
set -e

mkdir -p dist

# parser
script/generate-parser

# normal files
./node_modules/.bin/coffee \
  --bare \
  --compile \
  --output dist/ \
  source/

# cli
mkdir -p bin
BIN="bin/jadelet"
echo "#!/usr/bin/env node" | cat - dist/cli.js > "$BIN"
chmod +x "$BIN"
