#!/bin/bash

./node_modules/.bin/browserify dist/main.js --standalone Jadelet > jadelet.js
./node_modules/.bin/uglifyjs --compress --mangle - < jadelet.js > jadelet.min.js

./node_modules/.bin/browserify dist/runtime.js --standalone JadeletRuntime > jadelet-runtime.js
./node_modules/.bin/uglifyjs --compress --mangle - < jadelet-runtime.js > jadelet-runtime.min.js
