#!/bin/bash

./node_modules/.bin/browserify dist/main.js --standalone Hamlet > hamlet.js
./node_modules/.bin/uglifyjs --compress --mangle - < hamlet.js > hamlet.min.js

./node_modules/.bin/browserify dist/runtime.js --standalone HamletRuntime > hamlet-runtime.js
./node_modules/.bin/uglifyjs --compress --mangle - < hamlet-runtime.js > hamlet-runtime.min.js
