#!/bin/bash
set -e

script/prepublish

node_modules/.bin/mocha \
  --compilers coffee:coffee-script \
  --reporter spec \
  --require 'coffee-script/register' \
  --require test/helper.coffee \
  "$@"
