on: ["push", "pull_request"]

name: Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Setup Node.js 16.x
      uses: actions/setup-node@v2
      with:
        cache: yarn
        node-version: 16.x

    - name: Install and Test
      run: |
        yarn
        yarn test

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
